
create database WEB_TRUYEN_TRANH
USE WEB_TRUYEN_TRANH


CREATE TABLE USERS(
	 ID INT IDENTITY(1,1) NOT NULL UNIQUE,
	 FULLNAME NVARCHAR(50) NOT NULL,
	 EMAIL VARCHAR(50) NOT NULL,
	 PHONE VARCHAR(10) NOT NULL,
	 USERNAME VARCHAR(50),
	 PASSWORD VARCHAR(50) NOT NULL,
	 ROLE_USER INT DEFAULT 0,
	 PRIMARY KEY (USERNAME)
)
select * from USERS
insert into USERS (FULLNAME, EMAIL, PHONE, USERNAME, PASSWORD) 
VALUES (N'Nguyễn Đỗ Tường Phát','tuongphat208@gmail.com','012345689','tuongphat','tuongphat123')
insert into USERS (FULLNAME, EMAIL, PHONE, USERNAME, PASSWORD) 
VALUES(N'Triều Ninh Hấn','ninhhan208@gmail.com','0987654321','ninhhan','ninhhan123')
insert into USERS (FULLNAME, EMAIL, PHONE, USERNAME, PASSWORD) 
VALUES(N'Nguyên Cảnh','canhnguyen209@gmail.com','1092380891','canhnguyen','canhnguyen123')
insert into USERS (FULLNAME, EMAIL, PHONE, USERNAME, PASSWORD) 
VALUES(N'Văn Liêm','liemvan210@gmail.com','1293809812','liemnguyen','nguyenliem123')
insert into USERS (FULLNAME, EMAIL, PHONE, USERNAME, PASSWORD) 
VALUES(N'Nguyễn Văn Kiệt','vankiet200@gmail.com','0928172651','vankiet','vankiet123')


CREATE TABLE COMICS(
	ID INT IDENTITY(1,1),
	TITLE NVARCHAR(100) NOT NULL,
	DESCRIPTION NVARCHAR(200) NOT NULL,
	THUMBNAIL VARCHAR(200) NOT NULL,
	AUTHOR NVARCHAR(50) NOT NULL,
	STATUS NVARCHAR(50) NOT NULL,
	VIEWS INT DEFAULT 0,
	PRIMARY KEY (ID)
)

select * from COMICS
delete from comics
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'PHỤC THIÊN THÁNH CHỦ', N'Sinh tại tri mệnh lại bởi vì bệnh tương vẫn hắn vì chữa bệnh cải mệnh mà rời đi bước vào nhân gian Đại Đường','\assets\img\truyen1\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'TU TIÊN TRỞ VỀ TẠI VƯỜN TRƯỜNG', N'Luận tiềm lực, không tính thiên tài, có thể Huyền công võ kỹ, đều có thể vô sự tự thông.Luận mị lực','\assets\img\truyen2\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'THẦN CẤP THẤU THỊ', N'Trong vũ trụ bao la, một mảnh tinh hệ sinh diệt, cũng bất quá là sát na pha tạp lưu quang','\assets\img\truyen3\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'TU CHÂN TỨ VẠN NIÊN', N'Địa Cầu nguyên khí khôi phục, nhưng đây thật không phải cố sự Địa Cầu linh khí khôi phục','\assets\img\truyen4\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'THÂM DẠ THƯ ỐC', N'Dựng một cái thế lực, tuyên cổ trường tồn, vạn thế vinh danh.','\assets\img\truyen5\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'TỐI CƯỜNG THẦN THÚ HỆ THỐNG', N'Kết một đám bạn hữu, đều là truyền thuyết tồn tại.','\assets\img\truyen6\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'ĐẠP TOÁI TIÊN HÀ', N'Thế giới này có yêu, quỷ. Có giơ tay nhấc chân bài sơn đảo hải võ đạo đại năng.','\assets\img\truyen7\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'ĐỪNG CHỌC ĐỨA EM GÁI BÉ BỎNG CỦA CHÚNG TÔI', N'Trương Hùng lòng tin tràn trề muốn viết cho riêng mình một thiên truyền kỳ.','\assets\img\truyen8\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'TỒN TẠI VỚI TƯ CÁCH LÀ VỢ CỦA NAM CHÍNH', N'Nguyên chủ gọi Tống A Ngưu, tên này chú định là không có tiền đồ đấy.','\assets\img\truyen9\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'ĐIỀU TRA VIÊN CHUYỂN SINH', N'Một tiếng Trống Đồng chảy dọc thời thời không.','\assets\img\truyen10\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'YẾN SƠN PHÁI VÀ BÁCH HOA MÔN', N'Một thanh kiếm gánh vác thiên hạ số mệnh, Thuận Thiên mà thành.','\assets\img\truyen11\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'HƯỚNG TỚI ÁNH MẶT TRỜI', N'Tiên giới ngự tại cửu trọng thiên? Nhân gian phiêu dạt vô tận hải?','\assets\img\truyen12\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'GUNNER', N'Có những cố sự tồn tại ngươi không thể nào lường được đâu!','\assets\img\truyen13\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'SANTA', N'Dương gia dòng chính cầm theo hỗn độn châu, một đường quật khởi.','\assets\img\truyen14\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'SLIGHTLY SOUR SECRE', N'Trảm thánh, đăng tiên, chung kết thời đại.','\assets\img\truyen15\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'TRĂNG MỜ', N'Truyền thuyết hồng hoang từng nói về cuộc chiến giữa Tam Giới Lục Cõi.','\assets\img\truyen16\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'MAZE AGE Z', N'Khởi nguồn từ đứa con của Quỷ. Đứa trẻ đó sinh ra đã hấp thụ sinh mạng của mẹ mình, Ma Thần Vương cha của hắn vì đó mà hận hắn.','\assets\img\truyen17\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'ADONIS', N'Hắn được một Quỷ Vương khác nuôi dưỡng, nhưng hắn không có cảm xúc, không có tình người, không có bất kì khái niệm dục vọng nào.','\assets\img\truyen18\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'CÔ NÀNG MẠNH MẼ', N'Hắn chỉ một lòng cầu đạo khiến bản thân mạnh hơn.','\assets\img\truyen19\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'CẬU NHÓC TIỂU HỌC MÀ TÔI YÊU', N'Đến một lúc hắn trở nên quá mạnh, hắn dường như sẽ châm ngòi cho cuộc chiến Tam Giới, hắn sẽ gây nguy hại đến Lục Cõi chính hắn cũng không biết điều đó.','\assets\img\truyen20\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'CHUYỂN SINH THÀNH KIẾM', N'Vì thế hắn bị giết, hắn bị giết không phải vì hắn quá mạnh, hắn bị giết vì hắn đe dọa đến địa vị của anh chị em hắn, hắn có thể trở thành Ma Thần Vương đời kế tiếp, nên hắn bị giết.','\assets\img\truyen21\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'NGHỊCH THIÊN KIẾM THẦN', N'Bị giết bởi chính 12 anh chị em của mình.','\assets\img\truyen22\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'VÔ ĐỊCH KIẾM VỰC', N'Sau đó hắn phục sinh, hắn không trả thù, hắn chỉ một lòng cầu mong tìm ra bản ngã của mình.','\assets\img\truyen23\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'TINH LINH HUYỄN TƯỢNG KÝ TẠI DỊ GIỚI', N'Kiếp trước của hắn có hai người yêu hắn. Hắn không yêu bất cứ ai, hắn không có tình cảm.','\assets\img\truyen24\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'ĐẤU LA ĐẠI LỤC', N'Một người ở Ma Giới vì hắn chặt đứt một chân của mình bay đến cõi Địa Ngục tự sát chuyển sinh để nguyện cùng hắn trọn đời trọn kiếp.','\assets\img\truyen25\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'TUYỆT THẾ ĐƯỜNG MÔN', N'Một người là Thiên Thần cao cao tại thượng, biết tin hắn chết nàng đâm đầu xuống hạ giới tự vẫn.','\assets\img\truyen26\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'LONG VƯƠNG TRUYỀN THUYẾT', N'Sau đó nàng lại phục sinh để yêu hắn thêm một lần, chính nàng cũng không nhớ kiếp trước mình có yêu hắn.','\assets\img\truyen27\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'CHUNG CỰC ĐẤU LA', N'Nhưng khi gặp lại hắn ở kiếp sau, nàng lại yêu hắn thêm lần nữa. Nàng lại đau lòng thêm lần nữa.','\assets\img\truyen28\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'TỔ ĐIỀU TRA TRONG TRUYỀN THUYẾT TẠI ĐÔ THỊ', N'Hắn phục sinh chia ra làm bảy linh hồn, tồn tại ở bảy thế giới song song khác nhau.','\assets\img\truyen29\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'ENSA NO KUSABI', N'Vì để tìm ra bản ngã, hắn tự đấu tranh với chính hắn.','\assets\img\truyen30\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'NHẶT ĐƯỢC HOA KHÔI VỀ LÀM VỢ', N'Liệu các vị thần ở Tam Giới, các vị thần ở Lục Cõi sẽ cho hắn tập hợp lại chính mình, để chính hắn sinh ra một bản ngã.','\assets\img\truyen31\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'CỰC PHẨM TIÊN Y', N'Để chính hắn trở thành một hắn khác hoàn hảo hay không ?','\assets\img\truyen32\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'HỆ THỐNG ÉP TA LÀM NHÂN VẬT PHẢN DIỆN', N'Hắn sống có thể gây ra cuộc chiến Tam Giới Lục Cõi, hắn chết cuộc chiến ấy vẫn sẽ diễn ra ở một trạng thái cân bằng hơn.','\assets\img\truyen33\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'NAKA NO WARUI IINAZUKE NO HANASHI', N'Không còn là Ma Giới mạnh nhất, cũng không còn là Thiên Giới yếu hơn. Thiên Đình vào cuộc ngăn cản, hay Cõi Atula nơi các vị thần giận dữ đòi lại sự công bằng ?','\assets\img\truyen34\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'AIRE', N'Trảm phá phi thăng hàng rào, nghịch đổi Thiên Đạo pháp tắc!','\assets\img\truyen35\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'YUGI-OH', N'Thứ nhất thượng thần Hao Thần, thủ khai thần giới khơi dòng!','\assets\img\truyen36\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'ONEPUNCH MAN', N'Mã Vân Đằng cuối cùng một thế trọng sinh vì Thiên Nguyên Môn chưởng môn','\assets\img\truyen37\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'NARUTO FULL', N'Ở nơi đó, đại địa là phì nhiêu, tựa như sữa cùng mật chảy xuôi, ánh nắng là xán lạn, tựa hồ có thể tẩy đi rét lạnh cùng u ám.','\assets\img\truyen38\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'MAKIKOMARETE ISEKAI TENI SURU YATSU WA TAITEI CHEAT', N'Mọi người không cần lại đối mặt hoang vu, quái vật, cảm nhiễm, nhiễu sóng cùng các loại sự vật nguy hiểm.','\assets\img\truyen39\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'PHÁP SƯ KHÔNG PHÉP THUẬT', N'Ở nơi đó, hài tử là vui vẻ, trưởng thành là hạnh phúc, hết thảy đều là mỹ hảo.','\assets\img\truyen40\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'ĐẾ VƯƠNG TRẮC', N'Trên Đất Xám mỗi một vị học giả cổ vật, thợ săn di tích cùng nghiên cứu viên lịch sử đều biết, nơi này chính là thế giới mới.','\assets\img\truyen41\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'YÊU GIẢ VI VƯƠNG', N'Toàn cầu biến đổi lớn, nhân loại nguy cơ sớm tối, thiên đạo phần mềm bởi vì vận mà sinh!','\assets\img\truyen42\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'MANH SƯ TẠI THƯỢNG', N'Chu Hạo bắt đầu thu hoạch được trăm vạn may mắn giá trị, mù hộp mở ra một trăm linh tám tầng Long Tượng Bàn Nhược Công. . .','\assets\img\truyen43\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'TIÊN NGHỊCH', N'Mà lại hắn phát hiện, chỉ cần may mắn giá trị đủ nhiều, nữ thần may mắn đến làm ấm giường!','\assets\img\truyen44\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'NGUYÊN TÔN', N'Mà tại cái này yêu tộc, Trùng tộc hoành hành thế giới, thu hoạch may mắn giá trị đơn giản không nên quá đơn giản. . .','\assets\img\truyen45\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'YÊU THẦN KÝ', N'Một kiện gia gia di vật, để cho Tạ Vũ đời người xảy ra trước đó chưa từng có biến hóa.','\assets\img\truyen46\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'MAOU NO ORE GA DOREI ELF WO YOME NI SHITANDA GA DOU MEDEREBA II?', N'Trừng ác dương thiện, thay trời hành đạo.','\assets\img\truyen47\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'THIÊN Y PHƯỢNG CỬU', N'Không sai, cái này nói chính là ta.','\assets\img\truyen48\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'ANH HÙNG ? TA KHÔNG LÀM LÂU RỒI', N'Nhìn xem hệ thống định tốt trừng phạt cùng trợ giúp mới có ban thưởng người, dương đường nghĩa chính ngôn từ, quang minh lẫm liệt.','\assets\img\truyen49\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'NGÂN CHI THỦ MỘ NHÂN', N'Một giấc tỉnh lại, Trương Tiểu Kiếm trọng sinh đến cao trung thời kì .','\assets\img\truyen50\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'HOSHI NO AME TSUKI NO GEBOKU', N'Thế giới đại biến, linh khí sống lại, toàn dân tu luyện .','\assets\img\truyen51\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'XUYÊN VIỆT VƯƠNG PHI YẾU THĂNG CẤP', N'Nhiều năm sau này, Ngưu Canh lại được gọi là lương tâm xí nghiệp gia, tiếp nhận phóng viên mời riêng phỏng vấn.','\assets\img\truyen52\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'NƯƠNG TỬ NHÀ NÔNG CÓ HỈ RỒI', N'Các ngươi nhìn, Ngưu Tổng chính là như vậy một cái miệng ngại thể chính lại khiêm tốn nhân!','\assets\img\truyen53\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'NGƯỜI BẤT TỬ', N'Thế giới này xảy ra chuyện gì?','\assets\img\truyen54\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'CHƯ THIÊN KÝ', N'Cái kia mai táng tại bên trong dòng sông thời gian chân tướng lịch sử, ai đến lắng nghe?','\assets\img\truyen55\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'DANCHIGAI', N'Núi sông ngàn dặm viết thây nằm, càn khôn trăm năm tô lại hổ đói.','\assets\img\truyen56\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'TAMAYOMI', N'Thiên địa chí công như vô tình','\assets\img\truyen57\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'BẠCH CHỈ Y TIÊN', N'Ta có xích tâm một viên, lấy tuần thiên!','\assets\img\truyen58\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'ASOBI ASOBASE', N'Hoang Tiên Vực, từ xưa chính tà bất lưỡng lập!','\assets\img\truyen59\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'KURO NO SHOUKANSHI', N'Như thế nào chính?','\assets\img\truyen60\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'TRÊN NGƯỜI TA CÓ MỘT CON RỒNG', N'Như thế nào tà?','\assets\img\truyen61\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'TRỌNG SINH SAU TÁM VẠN NĂM', N'Đối mặt thế gian vạn hóa!','\assets\img\truyen62\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'NAM THÀNH CHỜ TRĂNG VỀ', N'Ta từ một kiếm lăng không trung, duy tiện tay bên trong một kiếm!','\assets\img\truyen63\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'NỮ CHỦ NGƯỜI ĐÀN ÔNG CỦA BẠN BỊ HỎNG RỒI', N'Vạn năm trước đó kiếm ý đệ nhất nhân Sở Kiếm Bạch, bị thất đại tông môn truy sát mà chết.','\assets\img\truyen64\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'TÔI LÀ LÍNH MỚI', N'Vạn năm về sau, hắn một lần nữa sống lại, đối mặt lại là một bộ xa lạ thân thể.','\assets\img\truyen65\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'CUỒNG LONG', N'Thất đại tông môn! Ta nhất định phải san bằng tất cả, trở thành Cửu Vực Đại Đế!','\assets\img\truyen66\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'SENRYUU SHOUJO', N'Ngụy Quân xác nhận chính mình sau khi bị giết chết là có thể trực tiếp vô địch, vì thế hắn bắt đầu điên cuồng tìm đường chết.','\assets\img\truyen67\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'ITS NOT MEGURO-SANS FIRST TIME', N'Sau đó, hắn phát hiện thế giới này có độc.','\assets\img\truyen68\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'HỌC SĨ TÁI SINH', N'Hèn mọn phát dục đầy thần trang, ngồi chờ đâm lưng ngược thái mạnh.','\assets\img\truyen69\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'VINH QUANG KIẾM', N'Đừng yêu ta, không có kết quả, chớ đến tình cảm thích khách chính là ta.','\assets\img\truyen70\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'NGHỊCH LÂN', N'Tay có la bàn phán Âm Dương, một tay pháp kiếm định càn khôn.','\assets\img\truyen71\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'NATSU NO ZENJITSU', N'Muội tử, ta nhìn ngươi cốt cách kỳ lạ, thiên phú dị bẩm, tới lại để cho ca cho ngươi sờ sờ cốt, chỉ điểm sai lầm.','\assets\img\truyen72\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'ANH HÙNG ? TA KHÔNG LÀM LÂU RỒI', N'Thân phụ Hồng hoang, thiên phú dị bẩm, huyền học ngũ thuật, mọi thứ tinh thông.','\assets\img\truyen73\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'TƯỚNG QUÂN! KHÔNG NÊN A!', N'20 rời núi, chém yêu tà, diệt Thi Sát, đấu ác quỷ, giết ma đầu!','\assets\img\truyen74\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'ĐẾ TẾ', N'Uống nhất liệt rượu, cua đẹp nhất nữu, giết nhất hung quỷ, giả bộ nhất ngưu bức.','\assets\img\truyen75\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'BỆ HẠ NHÀ TA MUỐN HẠI QUỐC', N'Nếu như một cá nhân bất hạnh về tới Thiên Khải năm thứ sáu.','\assets\img\truyen76\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'ĐỊCH ÚC ĐA CHI CA', N'Lúc này tình trạng vô vọng, yêm đảng hoành hành, bách quan đấu đá, dân chúng lầm than.','\assets\img\truyen77\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'YÊU ĐẠO CHÍ TÔN YÊU HOÀNG TRỞ VỀ', N'Đảng phái tranh giành như trước còn tại kéo dài.','\assets\img\truyen78\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'TÔI KHÔNG PHẢI QUỶ VƯƠNG', N'Yên Vũ Giang Nam bên trong, tài tử như trước mua vui, các giai nhân hát hay múa giỏi.','\assets\img\truyen79\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'THÔNG THẦN THỦ BIỆN', N'Các lưu dân áo rách quần manh, đói khát đã tới cực hạn.','\assets\img\truyen80\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'VẠN TỘC CHI KIẾP', N'Liêu Đông Hậu Kim thiết kỵ đã mài đao xoèn xoẹt, nhìn thèm thuồng thiên hạ.','\assets\img\truyen81\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'COLETTE WA SHINU KOTO NI SHITA', N'Mà đúng vào lúc này, Trương Tĩnh Nhất ngư phục gia thân, Tú Xuân Đao tại eo.','\assets\img\truyen82\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'ĐỒ ĐỆ NHÀ TA LẠI QUẢI RỒI', N'Hắn trở thành cái này thời đại, lấy hung tàn cùng bạo lực mà nổi tiếng thiên hạ Cẩm Y Vệ Giáo Úy.','\assets\img\truyen83\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'KẾ HOẠCH CÔNG LƯỢC CỦA CÔ VỢ GẢ THAY', N'Tại cái này không nói lý thời đại, vừa vặn trở thành cực kỳ không cần giảng đạo lý người.','\assets\img\truyen84\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'NGHỊCH THIÊN CHIẾN KỶ', N'Tỉnh lại sau giấc ngủ, Trần Mặc xuyên qua đến một cái kinh khủng khôi phục thế giới.','\assets\img\truyen85\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'KẺ PHẢN DIỆN LÀ MỘT CON RỐI', N'Còn trọng sinh thành một cái không thể động đậy người bù nhìn!','\assets\img\truyen86\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'ĐẰNG NỮ', N'Nhưng chỉ cần hấp thu hoảng sợ, Trần Mặc liền có thể không ngừng mạnh lên!','\assets\img\truyen87\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'SAO LẠI LÀ YÊU?', N'Từ đó, một cái kinh khủng đến cực điểm quỷ dị ra đời!','\assets\img\truyen88\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'HÃN PHI ĐƯƠNG GIA: LÃNH VƯƠNG XIN TỰ TRỌNG', N'Hắn bị mọi người xưng là Hoảng Sợ Ma Thần, Ác Mộng Chúa Tể, Tuyên Cổ Tà Thần. . .','\assets\img\truyen89\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'VẠN GIỚI TIÊN VƯƠNG', N'Hắn, liền là kinh khủng thời đại bên trong tồn tại cường đại nhất!','\assets\img\truyen90\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'TÔI MUỐN TRỞ THÀNH CÔ ẤY CHỈ MỘT NGÀY', N'Dạy thay trở về trường trên đường, ta liên tiếp làm hai trận quỷ dị mộng.','\assets\img\truyen91\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'VÂN TƯỞNG CHI CA: TRUY ÁI CHỈ LỆNH', N'Trong thôn bà cốt lại nói, đó không phải là mộng, là quỷ chiêu hồn.','\assets\img\truyen92\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'HỎA HỒNG NIÊN ĐẠI HẮC CỐT ĐƯỜNG', N'Từ đây, bên cạnh ta có thêm một cái lúc nào cũng muốn đem ta bổ nhào soái khí minh phu.','\assets\img\truyen93\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'THẺ ĐĂNG NHẬP PHONG ẤN SIÊU CẤP', N'Ta cũng bước lên không ngừng tao ngộ linh dị quỷ quái từ từ đường dài...','\assets\img\truyen94\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'NGHỊCH THIÊN CHIẾN THẦN', N'Xuyên qua đến một cái huyền huyễn đại thế giới.','\assets\img\truyen95\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'NEW PRINCE OF TENNIS', N'Nơi này có Sinh Mệnh Cấm Khu, nơi này có Chân Long kéo quan, nơi này có dị hỏa phần thiên, nơi này cũng có phía sau màn hắc thủ mưu toan tái diễn luân hồi. . .','\assets\img\truyen96\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'MINH NHẬT CHI KIẾP', N'Thế là, vì không kém gì người khác, vì mạnh lên, hắn chỉ có thể dựa vào bản thân cố gắng tu hành.','\assets\img\truyen97\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'VUA TRỘM MỘ', N'Thế nhân thần hóa thể nội ba trăm sáu mươi lăm khiếu huyệt?','\assets\img\truyen98\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'VÕ ĐẠO ĐỘC TÔN', N'Cơ Thiên Thần lại đem thể nội hạt bụi nhỏ tế bào coi như khiếu huyệt, thôi diễn ra Thần Tượng Trấn Ngục Kình!','\assets\img\truyen99\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
insert into COMICS (TITLE,DESCRIPTION,THUMBNAIL,AUTHOR,STATUS) 
VALUES (N'THÁI HẬU QUÂN HẠ THẦN', N'Ngọc Ngôn Tôn Thượng được xưng là tu tiên giới đệ nhất nhân, đợi 1 vạn 6000 năm cuối cùng cũng nhận được một đồ đệ, tỉ mỉ dạy bảo, che chở, sau đó . . . nàng quải','\assets\img\truyen100\thumbnail.png',N'Đang cập nhật',N'Chưa hoàn thành')
CREATE TABLE CHAPTERS(
	COMICID INT,
	CHAPTER INT,
	IMGID INT,
	CHAPTER_CONTENT_URL VARCHAR(50) NOT NULL
	PRIMARY KEY (COMICID, CHAPTER, IMGID),
	CONSTRAINT FK_CHAPTER_COMICID_COMIC FOREIGN KEY (COMICID) REFERENCES COMICS(ID)
)
insert into chapters VALUES (1,1,1,'\assets\img\truyen1\chap1\anh1.png')

select * from CHAPTERS
delete from CHAPTERS
CREATE TABLE COMMENTS (
	ID INT IDENTITY(1,1),
	COMICID INT NOT NULL,
	USERID INT NOT NULL,
	COMMENT NVARCHAR(200) NOT NULL,
	CREATED DATETIME DEFAULT GETDATE(),
	PRIMARY KEY (ID),
	CONSTRAINT FK_COMMENT_COMICID_COMIC FOREIGN KEY (COMICID) REFERENCES COMICS(ID),
	CONSTRAINT FK_COMMENT_USERID_COMIC FOREIGN KEY (USERID) REFERENCES USERS(ID),
)
insert into COMMENTS (COMICID,USERID,COMMENT)
values ('1','1',N'Truyên hay ghê á')
insert into COMMENTS (COMICID,USERID,COMMENT)
values ('1','2',N'Truyên này đúng với ý của mình luôn nà')
insert into COMMENTS (COMICID,USERID,COMMENT)
values ('2','1',N'Truyên thể loại mới à?')
insert into COMMENTS (COMICID,USERID,COMMENT)
values ('2','2',N'Cảnh main chính chết đau nòng t quá T_T')



select * from COMMENTS


CREATE TABLE TAGS(
	TAG NVARCHAR(50),
	COMICID INT,
	PRIMARY KEY (TAG, COMICID),
	CONSTRAINT FK_TAG_COMICID_COMIC FOREIGN KEY (COMICID) REFERENCES COMICS(ID),
)

delete  from TAGS



select * from COMICS inner join TAGS
on comics.id=tags.COMICID
order by comics.ID,tags.tag
insert into TAGS values (N'Ngôn tình',1)
insert into TAGS values (N'Phiêu lưu',1)
insert into TAGS values (N'Shounen',1)
insert into TAGS values (N'Drama',2)
insert into TAGS values (N'Giả tưởng',2)
insert into TAGS values (N'Hài hước',2)
insert into TAGS values (N'Giả tưởng',3)
insert into TAGS values (N'Hài hước',3)
insert into TAGS values (N'Hành động',3)
insert into TAGS values (N'Truyện màu',4)
insert into TAGS values (N'Xuyên không',4)
insert into TAGS values (N'Chuyển sinh',4)
insert into TAGS values (N'Ngôn tình',5)
insert into TAGS values (N'Phiêu lưu',5)
insert into TAGS values (N'Shounen',5)
insert into TAGS values (N'Shounen',6)
insert into TAGS values (N'Truyện màu',6)
insert into TAGS values (N'Xuyên không',6)
insert into TAGS values (N'Hài hước',7)
insert into TAGS values (N'Hành động',7)
insert into TAGS values (N'Học đường',7)
insert into TAGS values (N'Drama',8)
insert into TAGS values (N'Giả tưởng',8)
insert into TAGS values (N'Hài hước',8)
insert into TAGS values (N'Truyện màu',9)
insert into TAGS values (N'Xuyên không',9)
insert into TAGS values (N'Chuyển sinh',9)
insert into TAGS values (N'Phiêu lưu',10)
insert into TAGS values (N'Shounen',10)
insert into TAGS values (N'Truyện màu',10)
insert into TAGS values (N'Ngôn tình',11)
insert into TAGS values (N'Phiêu lưu',11)
insert into TAGS values (N'Shounen',11)
insert into TAGS values (N'Ngôn tình',12)
insert into TAGS values (N'Phiêu lưu',12)
insert into TAGS values (N'Shounen',12)
insert into TAGS values (N'Xuyên không',13)
insert into TAGS values (N'Chuyển sinh',13)
insert into TAGS values (N'Drama',13)
insert into TAGS values (N'Học đường',14)
insert into TAGS values (N'Kinh dị',14)
insert into TAGS values (N'Ngôn tình',14)
insert into TAGS values (N'Học đường',15)
insert into TAGS values (N'Kinh dị',15)
insert into TAGS values (N'Ngôn tình',15)
insert into TAGS values (N'Giả tưởng',16)
insert into TAGS values (N'Hài hước',16)
insert into TAGS values (N'Hành động',16)
insert into TAGS values (N'Chuyển sinh',17)
insert into TAGS values (N'Drama',17)
insert into TAGS values (N'Giả tưởng',17)
insert into TAGS values (N'Kinh dị',18)
insert into TAGS values (N'Ngôn tình',18)
insert into TAGS values (N'Phiêu lưu',18)
insert into TAGS values (N'Học đường',19)
insert into TAGS values (N'Kinh dị',19)
insert into TAGS values (N'Ngôn tình',19)
insert into TAGS values (N'Truyện màu',20)
insert into TAGS values (N'Xuyên không',20)
insert into TAGS values (N'Chuyển sinh',20)
insert into TAGS values (N'Giả tưởng',21)
insert into TAGS values (N'Hài hước',21)
insert into TAGS values (N'Hành động',21)
insert into TAGS values (N'Shounen',22)
insert into TAGS values (N'Truyện màu',22)
insert into TAGS values (N'Xuyên không',22)
insert into TAGS values (N'Hài hước',23)
insert into TAGS values (N'Hành động',23)
insert into TAGS values (N'Học đường',23)
insert into TAGS values (N'Xuyên không',24)
insert into TAGS values (N'Chuyển sinh',24)
insert into TAGS values (N'Drama',24)
insert into TAGS values (N'Truyện màu',25)
insert into TAGS values (N'Xuyên không',25)
insert into TAGS values (N'Chuyển sinh',25)
insert into TAGS values (N'Drama',26)
insert into TAGS values (N'Giả tưởng',26)
insert into TAGS values (N'Hài hước',26)
insert into TAGS values (N'Giả tưởng',27)
insert into TAGS values (N'Hài hước',27)
insert into TAGS values (N'Hành động',27)
insert into TAGS values (N'Ngôn tình',28)
insert into TAGS values (N'Phiêu lưu',28)
insert into TAGS values (N'Shounen',28)
insert into TAGS values (N'Chuyển sinh',29)
insert into TAGS values (N'Drama',29)
insert into TAGS values (N'Giả tưởng',29)
insert into TAGS values (N'Phiêu lưu',30)
insert into TAGS values (N'Shounen',30)
insert into TAGS values (N'Truyện màu',30)
insert into TAGS values (N'Ngôn tình',31)
insert into TAGS values (N'Phiêu lưu',31)
insert into TAGS values (N'Shounen',31)
insert into TAGS values (N'Giả tưởng',32)
insert into TAGS values (N'Hài hước',32)
insert into TAGS values (N'Hành động',32)
insert into TAGS values (N'Truyện màu',33)
insert into TAGS values (N'Xuyên không',33)
insert into TAGS values (N'Chuyển sinh',33)
insert into TAGS values (N'Chuyển sinh',34)
insert into TAGS values (N'Drama',34)
insert into TAGS values (N'Giả tưởng',34)
insert into TAGS values (N'Hài hước',35)
insert into TAGS values (N'Hành động',35)
insert into TAGS values (N'Học đường',35)
insert into TAGS values (N'Học đường',36)
insert into TAGS values (N'Kinh dị',36)
insert into TAGS values (N'Ngôn tình',36)
insert into TAGS values (N'Xuyên không',37)
insert into TAGS values (N'Chuyển sinh',37)
insert into TAGS values (N'Drama',37)
insert into TAGS values (N'Shounen',38)
insert into TAGS values (N'Truyện màu',38)
insert into TAGS values (N'Xuyên không',38)
insert into TAGS values (N'Hành động',39)
insert into TAGS values (N'Học đường',39)
insert into TAGS values (N'Kinh dị',39)
insert into TAGS values (N'Giả tưởng',40)
insert into TAGS values (N'Hài hước',40)
insert into TAGS values (N'Hành động',40)
insert into TAGS values (N'Giả tưởng',41)
insert into TAGS values (N'Hài hước',41)
insert into TAGS values (N'Hành động',41)
insert into TAGS values (N'Giả tưởng',42)
insert into TAGS values (N'Hài hước',42)
insert into TAGS values (N'Hành động',42)
insert into TAGS values (N'Drama',43)
insert into TAGS values (N'Giả tưởng',43)
insert into TAGS values (N'Hài hước',43)
insert into TAGS values (N'Hài hước',44)
insert into TAGS values (N'Hành động',44)
insert into TAGS values (N'Học đường',44)
insert into TAGS values (N'Shounen',45)
insert into TAGS values (N'Truyện màu',45)
insert into TAGS values (N'Xuyên không',45)
insert into TAGS values (N'Phiêu lưu',46)
insert into TAGS values (N'Shounen',46)
insert into TAGS values (N'Truyện màu',46)
insert into TAGS values (N'Học đường',47)
insert into TAGS values (N'Kinh dị',47)
insert into TAGS values (N'Ngôn tình',47)
insert into TAGS values (N'Phiêu lưu',48)
insert into TAGS values (N'Shounen',48)
insert into TAGS values (N'Truyện màu',48)
insert into TAGS values (N'Xuyên không',49)
insert into TAGS values (N'Chuyển sinh',49)
insert into TAGS values (N'Drama',49)
insert into TAGS values (N'Chuyển sinh',50)
insert into TAGS values (N'Drama',50)
insert into TAGS values (N'Giả tưởng',50)
insert into TAGS values (N'Drama',51)
insert into TAGS values (N'Giả tưởng',51)
insert into TAGS values (N'Hài hước',51)
insert into TAGS values (N'Hài hước',52)
insert into TAGS values (N'Hành động',52)
insert into TAGS values (N'Học đường',52)
insert into TAGS values (N'Kinh dị',53)
insert into TAGS values (N'Ngôn tình',53)
insert into TAGS values (N'Phiêu lưu',53)
insert into TAGS values (N'Hài hước',54)
insert into TAGS values (N'Hành động',54)
insert into TAGS values (N'Học đường',54)
insert into TAGS values (N'Kinh dị',55)
insert into TAGS values (N'Ngôn tình',55)
insert into TAGS values (N'Phiêu lưu',55)
insert into TAGS values (N'Ngôn tình',56)
insert into TAGS values (N'Phiêu lưu',56)
insert into TAGS values (N'Shounen',56)
insert into TAGS values (N'Hài hước',57)
insert into TAGS values (N'Hành động',57)
insert into TAGS values (N'Học đường',57)
insert into TAGS values (N'Phiêu lưu',58)
insert into TAGS values (N'Shounen',58)
insert into TAGS values (N'Truyện màu',58)
insert into TAGS values (N'Xuyên không',59)
insert into TAGS values (N'Chuyển sinh',59)
insert into TAGS values (N'Drama',59)
insert into TAGS values (N'Hành động',60)
insert into TAGS values (N'Học đường',60)
insert into TAGS values (N'Kinh dị',60)
insert into TAGS values (N'Xuyên không',61)
insert into TAGS values (N'Chuyển sinh',61)
insert into TAGS values (N'Drama',61)
insert into TAGS values (N'Ngôn tình',62)
insert into TAGS values (N'Phiêu lưu',62)
insert into TAGS values (N'Shounen',62)
insert into TAGS values (N'Shounen',63)
insert into TAGS values (N'Truyện màu',63)
insert into TAGS values (N'Xuyên không',63)
insert into TAGS values (N'Truyện màu',64)
insert into TAGS values (N'Xuyên không',64)
insert into TAGS values (N'Chuyển sinh',64)
insert into TAGS values (N'Truyện màu',65)
insert into TAGS values (N'Xuyên không',65)
insert into TAGS values (N'Chuyển sinh',65)
insert into TAGS values (N'Kinh dị',66)
insert into TAGS values (N'Ngôn tình',66)
insert into TAGS values (N'Phiêu lưu',66)
insert into TAGS values (N'Chuyển sinh',67)
insert into TAGS values (N'Drama',67)
insert into TAGS values (N'Giả tưởng',67)
insert into TAGS values (N'Phiêu lưu',68)
insert into TAGS values (N'Shounen',68)
insert into TAGS values (N'Truyện màu',68)
insert into TAGS values (N'Hài hước',69)
insert into TAGS values (N'Hành động',69)
insert into TAGS values (N'Học đường',69)
insert into TAGS values (N'Học đường',70)
insert into TAGS values (N'Kinh dị',70)
insert into TAGS values (N'Ngôn tình',70)
insert into TAGS values (N'Kinh dị',71)
insert into TAGS values (N'Ngôn tình',71)
insert into TAGS values (N'Phiêu lưu',71)
insert into TAGS values (N'Truyện màu',72)
insert into TAGS values (N'Xuyên không',72)
insert into TAGS values (N'Chuyển sinh',72)
insert into TAGS values (N'Hành động',73)
insert into TAGS values (N'Học đường',73)
insert into TAGS values (N'Kinh dị',73)
insert into TAGS values (N'Ngôn tình',74)
insert into TAGS values (N'Phiêu lưu',74)
insert into TAGS values (N'Shounen',74)
insert into TAGS values (N'Giả tưởng',75)
insert into TAGS values (N'Hài hước',75)
insert into TAGS values (N'Hành động',75)
insert into TAGS values (N'Hành động',76)
insert into TAGS values (N'Học đường',76)
insert into TAGS values (N'Kinh dị',76)
insert into TAGS values (N'Truyện màu',77)
insert into TAGS values (N'Xuyên không',77)
insert into TAGS values (N'Chuyển sinh',77)
insert into TAGS values (N'Ngôn tình',78)
insert into TAGS values (N'Phiêu lưu',78)
insert into TAGS values (N'Shounen',78)
insert into TAGS values (N'Xuyên không',79)
insert into TAGS values (N'Chuyển sinh',79)
insert into TAGS values (N'Drama',79)
insert into TAGS values (N'Xuyên không',80)
insert into TAGS values (N'Chuyển sinh',80)
insert into TAGS values (N'Drama',80)
insert into TAGS values (N'Học đường',81)
insert into TAGS values (N'Kinh dị',81)
insert into TAGS values (N'Ngôn tình',81)
insert into TAGS values (N'Shounen',82)
insert into TAGS values (N'Truyện màu',82)
insert into TAGS values (N'Xuyên không',82)
insert into TAGS values (N'Phiêu lưu',83)
insert into TAGS values (N'Shounen',83)
insert into TAGS values (N'Truyện màu',83)
insert into TAGS values (N'Drama',84)
insert into TAGS values (N'Giả tưởng',84)
insert into TAGS values (N'Hài hước',84)
insert into TAGS values (N'Hành động',85)
insert into TAGS values (N'Học đường',85)
insert into TAGS values (N'Kinh dị',85)
insert into TAGS values (N'Xuyên không',86)
insert into TAGS values (N'Chuyển sinh',86)
insert into TAGS values (N'Drama',86)
insert into TAGS values (N'Hành động',87)
insert into TAGS values (N'Học đường',87)
insert into TAGS values (N'Kinh dị',87)
insert into TAGS values (N'Ngôn tình',88)
insert into TAGS values (N'Phiêu lưu',88)
insert into TAGS values (N'Shounen',88)
insert into TAGS values (N'Ngôn tình',89)
insert into TAGS values (N'Phiêu lưu',89)
insert into TAGS values (N'Shounen',89)
insert into TAGS values (N'Phiêu lưu',90)
insert into TAGS values (N'Shounen',90)
insert into TAGS values (N'Truyện màu',90)
insert into TAGS values (N'Xuyên không',91)
insert into TAGS values (N'Chuyển sinh',91)
insert into TAGS values (N'Drama',91)
insert into TAGS values (N'Ngôn tình',92)
insert into TAGS values (N'Phiêu lưu',92)
insert into TAGS values (N'Shounen',92)
insert into TAGS values (N'Kinh dị',93)
insert into TAGS values (N'Ngôn tình',93)
insert into TAGS values (N'Phiêu lưu',93)
insert into TAGS values (N'Chuyển sinh',94)
insert into TAGS values (N'Drama',94)
insert into TAGS values (N'Giả tưởng',94)
insert into TAGS values (N'Ngôn tình',95)
insert into TAGS values (N'Phiêu lưu',95)
insert into TAGS values (N'Shounen',95)
insert into TAGS values (N'Phiêu lưu',96)
insert into TAGS values (N'Shounen',96)
insert into TAGS values (N'Truyện màu',96)
insert into TAGS values (N'Ngôn tình',97)
insert into TAGS values (N'Phiêu lưu',97)
insert into TAGS values (N'Shounen',97)
insert into TAGS values (N'Học đường',98)
insert into TAGS values (N'Kinh dị',98)
insert into TAGS values (N'Ngôn tình',98)
insert into TAGS values (N'Shounen',99)
insert into TAGS values (N'Truyện màu',99)
insert into TAGS values (N'Xuyên không',99)
insert into TAGS values (N'Chuyển sinh',100)
insert into TAGS values (N'Drama',100)
insert into TAGS values (N'Giả tưởng',100)







CREATE TABLE INTERACTIONS(
	COMICID INT,
	USERID INT,
	FAVOR BIT DEFAULT 0,
	DISFAVOR BIT DEFAULT 0,
	FOLLOW BIT DEFAULT 0,
	PRIMARY KEY (COMICID, USERID),
	CONSTRAINT FK_INTERACTION_COMICID_COMIC FOREIGN KEY (COMICID) REFERENCES COMICS(ID),
	CONSTRAINT FK_INTERACTION_USERID_COMIC FOREIGN KEY (USERID) REFERENCES USERS(ID),
)
insert into INTERACTIONS (comicid,USERID)
values ('1','1')
select * from INTERACTIONS








CREATE TABLE HISTORIES(
	USERID INT,
	COMICID INT,
	CREATED DATETIME DEFAULT GETDATE(),
	ISREAD BIT DEFAULT 0,
	PRIMARY KEY (COMICID, USERID),
	CONSTRAINT FK_HISTORY_COMICID_COMIC FOREIGN KEY (COMICID) REFERENCES COMICS(ID),
	CONSTRAINT FK_HISTORY_USERID_COMIC FOREIGN KEY (USERID) REFERENCES USERS(ID),
)

/*LỆNH KIỂM TRA THUỘC TÍNH BẢNG*/
EXEC sp_help USERS
EXEC sp_help COMICS
EXEC sp_help CHAPTERS
EXEC sp_help TAGS
EXEC sp_help COMMENTS
EXEC sp_help INTERACTIONS
EXEC sp_help HISTORIES



SELECT TABLE_NAME, COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS

insert into histories (USERID,COMICID,CREATED) values (27,1, GETDATE())
select * from HISTORIES

select * from comics

select * from USERS

delete from HISTORIES
delete from USERS 

/*Hàm reset Identity*/
DBCC CHECKIDENT ('USERS', RESEED, 0)  


