
create database WEB_TRUYEN_TRANH
USE WEB_TRUYEN_TRANH


CREATE TABLE USERS(
	 ID INT IDENTITY(1,1) NOT NULL UNIQUE,
	 FULLNAME NVARCHAR(50) NOT NULL,
	 EMAIL VARCHAR(50) NOT NULL,
	 PHONE VARCHAR(10) NOT NULL,
	 USERNAME VARCHAR(50),
	 PASSWORD VARCHAR(50) NOT NULL,
	 ROLE_USER INT DEFAULT 0,
	 PRIMARY KEY (USERNAME)
)
CREATE TABLE COMICS(
	ID INT IDENTITY(1,1),
	TITLE NVARCHAR(50) NOT NULL,
	DESCRIPTION NVARCHAR(50) NOT NULL,
	THUMBNAIL VARCHAR(50) NOT NULL,
	AUTHOR NVARCHAR(50) NOT NULL,
	STATUS NVARCHAR(50) NOT NULL,
	VIEWS INT DEFAULT 0,
	PRIMARY KEY (ID)
)
CREATE TABLE CHAPTERS(
	CONTENTID INT,
	CHAPTER INT,
	COMICID INT,
	CHAPTER_CONTENT_URL VARCHAR(50) NOT NULL,
	PRIMARY KEY (CONTENTID, CHAPTER, COMICID),
	CONSTRAINT FK_CHAPTER_COMICID_COMIC FOREIGN KEY (COMICID) REFERENCES COMICS(ID)
)
CREATE TABLE COMMENTS (
	ID INT IDENTITY(1,1),
	COMICID INT NOT NULL,
	USERID INT NOT NULL,
	COMMENT NVARCHAR(200) NOT NULL,
	CREATED DATETIME DEFAULT GETDATE(),
	PRIMARY KEY (ID),
	CONSTRAINT FK_COMMENT_COMICID_COMIC FOREIGN KEY (COMICID) REFERENCES COMICS(ID),
	CONSTRAINT FK_COMMENT_USERID_COMIC FOREIGN KEY (USERID) REFERENCES USERS(ID),
)
CREATE TABLE TAGS(
	TAG NVARCHAR(50),
	COMICID INT,
	PRIMARY KEY (TAG, COMICID),
	CONSTRAINT FK_TAG_COMICID_COMIC FOREIGN KEY (COMICID) REFERENCES COMICS(ID),
)
CREATE TABLE INTERACTIONS(
	COMICID INT,
	USERID INT,
	FAVOR BIT DEFAULT 0,
	DISFAVOR BIT DEFAULT 0,
	FOLLOW BIT DEFAULT 0,
	PRIMARY KEY (COMICID, USERID),
	CONSTRAINT FK_INTERACTION_COMICID_COMIC FOREIGN KEY (COMICID) REFERENCES COMICS(ID),
	CONSTRAINT FK_INTERACTION_USERID_COMIC FOREIGN KEY (USERID) REFERENCES USERS(ID),
)
CREATE TABLE HISTORIES(
	USERID INT,
	COMICID INT,
	CREATED DATETIME DEFAULT GETDATE(),
	ISREAD BIT DEFAULT 0,
	PRIMARY KEY (COMICID, USERID),
	CONSTRAINT FK_HISTORY_COMICID_COMIC FOREIGN KEY (COMICID) REFERENCES COMICS(ID),
	CONSTRAINT FK_HISTORY_USERID_COMIC FOREIGN KEY (USERID) REFERENCES USERS(ID),
)

/*LỆNH KIỂM TRA THUỘC TÍNH BẢNG*/
EXEC sp_help USERS
EXEC sp_help COMICS
EXEC sp_help CHAPTERS
EXEC sp_help TAGS
EXEC sp_help COMMENTS
EXEC sp_help INTERACTIONS
EXEC sp_help HISTORIES



SELECT TABLE_NAME, COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS

insert into USERS (FULLNAME, EMAIL, PHONE, USERNAME, PASSWORD) 
VALUES (N'Nguyễn Đỗ Tường Phát','tuongphat208@gmail.com','12345689','tuongphat','tuongphat123')
insert into USERS (FULLNAME, EMAIL, PHONE, USERNAME, PASSWORD) 
VALUES(N'Lường Thị Thu Nguyệt','18520329@gm.uit.edu.vn','123456789','thunguyet','123')
insert into USERS (FULLNAME, EMAIL, PHONE, USERNAME, PASSWORD) 
VALUES(N'Nguyễn Tuấn Cảnh','18520513@gm.uit.edu.vn','123456789','tuancanh','123')
insert into COMICS (TITLE, DESCRIPTION, IMG_URL,AUTHOR,STATUS) values (N'Hấn óc chó', N'Hấn óc chó', '/jsdhfkjsfhkjs', 'Hấn', 'Đang ngáo')
insert into histories (USERID,COMICID,CREATED) values (27,1, GETDATE())
select * from HISTORIES

select * from comics

select * from USERS

delete from HISTORIES
delete from USERS 

/*Hàm reset Identity*/
DBCC CHECKIDENT ('USERS', RESEED, 0)  